hapi:
  fhir:
    version: R4
    allow_external_references: true
    allow_multiple_delete: true
    reuse_cached_search_results_millis: 60000
    retain_cached_searches_mins: 10
    # Disable implementation guides entirely
    implementationguides: {}
    # Disable validation and profiles that are memory-intensive
    validation:
      enabled: false
    # Use a simple in-memory database (optional, depending on your use case)
    database:
      connection:
        type: h2

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  main:
    lazy-initialization: true
